---

- name: Create LTM FTP Monitor
  f5bigip_ltm_monitor_ftp:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ monitor_name }}"
    partition: "{{ bigip_partition }}"
    description: "{{ monitor_description }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Create LTM FTP Monitor
  assert:
    that:
      - result|changed

- name: Create LTM FTP Monitor (idempotent)
  f5bigip_ltm_monitor_ftp:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ monitor_name }}"
    partition: "{{ bigip_partition }}"
    description: "{{ monitor_description }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Create LTM FTP Monitor (idempotent)
  assert:
    that:
      - not result|changed

- name: Change LTM FTP Monitor description, interval and timeout
  f5bigip_ltm_monitor_ftp:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ monitor_name }}"
    partition: "{{ bigip_partition }}"
    description: "new {{ monitor_description }}"
    interval: "{{ monitor_interval }}"
    timeout: "{{ monitor_timeout }}"
  delegate_to: localhost
  register: result

- name: Assert Change LTM FTP Monitor description, interval and timeout
  assert:
    that:
      - result|changed

- name: Change LTM FTP Monitor description, interval and timeout (idempotent)
  f5bigip_ltm_monitor_ftp:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ monitor_name }}"
    partition: "{{ bigip_partition }}"
    description: "new {{ monitor_description }}"
    interval: "{{ monitor_interval }}"
    timeout: "{{ monitor_timeout }}"
  delegate_to: localhost
  register: result

- name: Assert Change LTM FTP Monitor description, interval and timeout (idempotent)
  assert:
    that:
      - not result|changed

- name: Delete LTM FTP Monitor
  f5bigip_ltm_monitor_ftp:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ monitor_name }}"
    partition: "{{ bigip_partition }}"
    state: absent
  delegate_to: localhost
  register: result

- name: Assert Delete LTM FTP Monitor
  assert:
    that:
      - result|changed

- name: Delete LTM FTP Monitor (idempotent)
  f5bigip_ltm_monitor_ftp:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ monitor_name }}"
    partition: "{{ bigip_partition }}"
    state: absent
  delegate_to: localhost
  register: result

- name: Assert Delete LTM FTP Monitor (idempotent)
  assert:
    that:
      - not result|changed