---

- name: Create NET ARP
  f5bigip_net_arp:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ arp_name }}"
    partition: "{{ bigip_partition }}"
    description: "{{ arp_description }}"
    ip_address: "{{ arp_ip_address }}"
    mac_address: "{{ arp_mac_address }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Create NET ARP
  assert:
    that:
      - result|changed

- name: Create NET ARP (idempotent)
  f5bigip_net_arp:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ arp_name }}"
    partition: "{{ bigip_partition }}"
    description: "{{arp_description }}"
    ip_address: "{{ arp_ip_address }}"
    mac_address: "{{ arp_mac_address }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Create NET ARP (idempotent)
  assert:
    that:
      - not result|changed

- name: Change NET ARP description and mac address
  f5bigip_net_arp:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ arp_name }}"
    partition: "{{ bigip_partition }}"
    description: "new {{ arp_description }}"
    mac_address: "{{ arp_mac_address_new }}"
  register: result

- name: Assert Change NET ARP description and mac address
  assert:
    that:
      - result|changed

- name: Change NET ARP description and mac address (idempotent)
  f5bigip_net_arp:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ arp_name }}"
    partition: "{{ bigip_partition }}"
    description: "new {{ arp_description }}"
    mac_address: "{{ arp_mac_address_new }}"
  register: result

- name: Assert Change NET ARP description and mac address (idempotent)
  assert:
    that:
      - not result|changed

- name: Delete NET ARP
  f5bigip_net_arp:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ arp_name }}"
    partition: "{{ bigip_partition }}"
    state: absent
  delegate_to: localhost
  register: result

- name: Assert Delete NET ARP
  assert:
    that:
      - result|changed

- name: Delete NET ARP (idempotent)
  f5bigip_net_arp:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ arp_name }}"
    partition: "{{ bigip_partition }}"
    state: absent
  delegate_to: localhost
  register: result

- name: Assert Delete NET ARP (idempotent)
  assert:
    that:
      - not result|changed