---

- name: Create LTM FTP Profile
  f5bigip_ltm_profile_ftp:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    name: "{{ profile_name }}"
    partition: "{{ bigip_partition }}"
    description: "{{ profile_description }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Create LTM FTP Profile
  assert:
    that:
      - result|changed
  
- name: Create LTM FTP Profile (idempotent)
  f5bigip_ltm_profile_ftp:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    name: "{{ profile_name }}"
    partition: "{{ bigip_partition }}"
    description: "{{ profile_description }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Create LTM FTP Profile (idempotent)
  assert:
    that:
      - not result|changed

- name: Change LTM FTP Profile description
  f5bigip_ltm_profile_ftp:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    name: "{{ profile_name }}"
    partition: "{{ bigip_partition }}"
    description: "new {{ profile_description }}"
  delegate_to: localhost
  register: result

- name: Assert Change LTM FTP Profile description
  assert:
    that:
      - result|changed

- name: Change LTM FTP Profile description (idempotent)
  f5bigip_ltm_profile_ftp:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    name: "{{ profile_name }}"
    partition: "{{ bigip_partition }}"
    description: "new {{ profile_description }}"
  delegate_to: localhost
  register: result

- name: Assert Change LTM FTP Profile description (idempotent)
  assert:
    that:
      - not result|changed

- name: Delete LTM FTP Profile
  f5bigip_ltm_profile_ftp:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    name: "{{ profile_name }}"
    partition: "{{ bigip_partition }}"
    state: absent
  delegate_to: localhost
  register: result

- name: Assert Delete LTM FTP Profile
  assert:
    that:
      - result|changed

- name: Delete LTM FTP Profile (idempotent)
  f5bigip_ltm_profile_ftp:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    name: "{{ profile_name }}"
    partition: "{{ bigip_partition }}"
    state: absent
  delegate_to: localhost
  register: result

- name: Assert Delete LTM FTP Profile (idempotent)
  assert:
    that:
      - not result|changed